FROM python:3.12-slim

WORKDIR /app

# System deps
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc libpq-dev curl \
    && rm -rf /var/lib/apt/lists/*

# Python deps
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip "setuptools<82" wheel \
    && pip install --no-cache-dir -r requirements.txt

# Copy project
COPY . .

# Create logs dir
RUN mkdir -p logs

# 🔥 RUN PIPELINE (instead of uvicorn)
CMD ["python", "pipeline/daily.py"]