-- ============================================================
-- Seed: All 40 NSE Indices
-- ============================================================
INSERT INTO indices (index_name, index_category) VALUES
('Nifty 50',            'broad'),
('Nifty Next 50',       'broad'),
('Nifty 100',           'broad'),
('Nifty 200',           'broad'),
('Nifty 500',           'broad'),
('Nifty Midcap 50',     'broad'),
('Nifty Midcap 100',    'broad'),
('Nifty Midcap 150',    'broad'),
('Nifty Smallcap 50',   'broad'),
('Nifty Smallcap 100',  'broad'),
('Nifty Smallcap 250',  'broad'),
('Nifty Microcap 250',  'broad'),
('Nifty Auto',                  'sector'),
('Nifty Bank',                  'sector'),
('Nifty Energy',                'sector'),
('Nifty Financial Services',    'sector'),
('Nifty FMCG',                  'sector'),
('Nifty IT',                    'sector'),
('Nifty Media',                 'sector'),
('Nifty Metal',                 'sector'),
('Nifty MNC',                   'sector'),
('Nifty Pharma',                'sector'),
('Nifty PSU Bank',              'sector'),
('Nifty Realty',                'sector'),
('Nifty India Consumption',     'sector'),
('Nifty Commodities',           'sector'),
('Nifty Infrastructure',        'sector'),
('Nifty PSE',                   'sector'),
('Nifty Services Sector',       'sector'),
('Nifty CPSE',                  'sector'),
('Nifty Private Bank',          'sector'),
('Nifty Oil And Gas',           'sector'),
('Nifty India Defence',         'sector'),
('Nifty Rural',                 'sector'),
('Nifty Capital Markets',       'sector'),
('Nifty Consumer Durables',     'sector'),
('Nifty India Tourism',         'sector'),
('Nifty India Internet',        'sector'),
('Nifty Chemicals',             'sector'),
('Nifty India Manufacturing',   'sector')
ON CONFLICT (index_name) DO NOTHING;
